name: Publish Docker image

on:
  push:
    branches:
      - "*" # matches every branch that doesn't contain a '/'
      - "*/*" # matches every branch containing a single '/'
      - "**" # matches every branch
      - "!main" # excludes master
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
      - name: Check out the repo
        run: git clone --depth 1 https://github.com/OpenBMB/XAgent.git
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build images
        run: |
          for i in ToolServerManager ToolServerNode ToolServerMonitor; do
            docker build -f XAgent/dockerfiles/$i/Dockerfile -t huodon/xagent-$i:latest ./XAgent
          done
      - name: Push images
        run: |
          docker push huodon/{ToolServerManager,ToolServerNode,ToolServerMonitor}:latest
